# Name of the run. For output directory and wandb.
name: ukbb_sex_eval_capi

# Prediction task
task: classification

# Datasets
datasets:
  ukbb-train:
    root: /teamspace/gcs_folders/share/fmri-fm/datasets/flat-clips/ukbb-train-clips-16t
    shuffle: true

  ukbb-val:
    root: /teamspace/gcs_folders/share/fmri-fm/datasets/flat-clips/ukbb-val-clips-16t
    shuffle: false

  ukbb-test:
    root: /teamspace/gcs_folders/share/fmri-fm/datasets/flat-clips/ukbb-test-clips-16t
    shuffle: false

# Dataset names for special subsets.
train_dataset: ukbb-train
val_dataset: ukbb-val
test_dataset: ukbb-test

# # Target ID map, if not already in the samples.
# target_id_map: /teamspace/gcs_folders/share/fmri-fm/datasets/ukbb_sex_target_id_map.json
# target_key: sub

pretrain_ckpt: /teamspace/studios/this_studio/fmri-fm/checkpoints/pretrain_capi_vit_b_ps16_mae_defaults/checkpoint-last.pth

wandb_project: fMRI-foundation-model-eval

# Number of target classes
num_classes: 2


