# Name of the run. For output directory and wandb.
name: nsd_clip_class_eval

# Prediction task
#   - classification
#   - regression
task: classification

# Datasets
datasets:
- name: nsd-train
  root: datasets/flat-clips/nsd-train-task-clips-16t
  split_range: [0.0, 0.9]
  shuffle: true

- name: nsd-train-subset
  root: datasets/flat-clips/nsd-train-task-clips-16t
  split_range: [0.0, 0.1]
  shuffle: false

- name: nsd-train-holdout
  root: datasets/flat-clips/nsd-train-task-clips-16t
  split_range: [0.9, 1.0]
  shuffle: false

- name: nsd-val
  root: datasets/flat-clips/nsd-val-task-clips-16t
  shuffle: false

- name: nsd-test
  root: datasets/flat-clips/nsd-test-task-clips-16t
  shuffle: false

- name: nsd-test-ood
  root: datasets/flat-clips/nsd-test-ood-task-clips-16t
  shuffle: false

# Dataset names for special subsets.
train_dataset_name: nsd-train
val_dataset_name: nsd-val
test_dataset_name: nsd-test

# Target ID map, if not already in the samples.
target_id_map: null
target_key: null

# Number of target classes for classification, or target dimension for regression.
num_classes: 41
