# Name of the run. For output directory and wandb.
name: ukbb_sex_eval

# Prediction task
#   - classification
#   - regression
task: classification

# Datasets
datasets:
- name: ukbb-train
  root: datasets/flat-clips/ukbb-train-clips-16t
  shuffle: true

- name: ukbb-val
  root: datasets/flat-clips/ukbb-val-clips-16t
  shuffle: false

- name: ukbb-test
  root: datasets/flat-clips/ukbb-test-clips-16t
  shuffle: false

# Dataset names for special subsets.
train_dataset_name: ukbb-train
val_dataset_name: ukbb-val
test_dataset_name: ukbb-test

# Target ID map, if not already in the samples.
target_id_map: datasets/ukbb-phenotype/sex_target_id_map.json
target_key: sub

# Number of target classes for classification, or target dimension for regression.
num_classes: 2
